import = ["/home/subzero/.config/alacritty/monokai_charcoal.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500 
unfocused_hollow = false

[cursor.style]
shape = "Underline"
blinking = "Always"

[font]
size = 10.8

[font.normal]
family = "Space Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
