window:
  padding:
    x: 10
    y: 10
  class:
    instance: Alacritty
    general: Alacritty
    opacity: 0.8

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Space Mono
    style:  Regular
  size: 12 
draw_bold_text_with_bright_colors: true

cursor:
  style: Underline
  blinking: on
  unfocused_hollow: false
  unfocused_opacity: 1.0

import:
  - ~/.config/alacritty/monokai_charcoal.yaml

selection:
  save_to_clipboard: false

shell:
  program: /usr/bin/bash

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }

